### ISSUE TITLE
Add color swatches for interactive notebooks?

### ISSUE THREAD

**Issue by AJMansfield** [edaniszewski/colorutils#12]
I actually just made a fork with a very basic implementation of this for my own use, although I don't think the code I have is exactly ready for prime time or anything.

But basically, by adding a function like `_repr_html_` to the `Color` object, interactive notebook environments like Jupyter or IPython can provide a richer display representation for these objects; in this case it would be quite useful to use this to provide a color swatch of some sort.

The code I added currently just displays a colored box with the hex code above it, like this:
![blue color swatch](https://user-images.githubusercontent.com/3825306/98000071-121dd680-1dba-11eb-84b3-03fd9161e3ef.png)

I'm sure someone else could figure out an even neater layout for this (perhaps put the hex code, rgb triple, hsv, etc to the right of the swatch?), though.

For reference, to get this I added this function to the definition of `Color`:

```python
def _repr_html_(self):
    return '''
        <div style="
            width:80px;
            text-align:center;
        ">
            <code>{0}</code>
        </div>
        <div style="
            background-color:{0};
            width:80px;
            height:80px;
            border-style:solid;
            border-width:2px
        "></div>'''.format(self.hex)
```

**Comment by edaniszewski** [comment]
This is pretty neat and not something I had thought of. I can for  sure look into adding  this as a feature, or if you'd like to open a PR with your work, I'll gladly accept it too (:

**Comment by AJMansfield** [comment]
Sure, although I have a few more changes I wanna make to the formatting first, just to make the color swatch display a bit cleaner. I'll make a PR probably tomorrow once I've edited it to make the information display a bit better.
